# Generated by Django 5.1.3 on 2025-01-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_ex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyconversion',
            old_name='form_currency',
            new_name='from_currency',
        ),
    ]
