# Generated by Django 5.1.3 on 2025-01-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_ex', '0002_rename_form_currency_currencyconversion_from_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyconversion',
            options={},
        ),
    ]
