# Generated by Django 5.1.3 on 2025-01-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_ex', '0004_alter_currencyconversion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='currencyconversion',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
